version: '3.8'

services:
  # Наша база данных PostgreSQL
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    # Сервер больше не собирает код, а качает готовую "коробку" из твоего GitHub
    image: ghcr.io/maglevchik/maglevchik-ci_cd_pipeline1:latest
    container_name: django_app
    restart: always
    env_file:
      - .env
    # Порт 80 убрали отсюда, так как теперь его будет слушать Nginx
    expose:
      - "8000"
    command: gunicorn bot_builder.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      # Подключаем файл настроек Nginx, который создадим в следующем шаге
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static
    depends_on:
      - web

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  static_volume:
