name: CI/CD Pipeline with Docker Compose

# Запускаем пайплайн при каждом пуше в основную ветку
on:
  push:
    branches:
      - main
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Скачиваем свежий код из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Устанавливаем нужные библиотеки
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 3. Запускаем тестирование (CI)
      - name: Run tests
        run: python manage.py test

      # 4. Отправляем проверенный код на VPS (CD - Копирование)
      - name: Copy files to VPS
        if: success() # Выполнится только если тесты прошли без ошибок
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/root/Maglevchik-CI_CD_pipeline1"

      # 5. Разворачиваем проект через Docker Compose (CD - Запуск)
      - name: Deploy with Docker Compose
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/Maglevchik-CI_CD_pipeline1
            docker-compose down
            docker-compose up -d --build
